//! Extract PE sections from a League client binary and produce a
//! `.patch` archive skeleton that our emulator backend can partially
//! consume.
//!
//! Only the mechanical half is automated here (parse the PE, dump
//! `.text` / `.data` / `.rdata` raw bytes, write a `result.json`
//! skeleton with placeholder RVAs). Filling in the RVAs of the two
//! decoder functions, the two allocator stubs, the safety-check stub,
//! and the per-field struct offsets is a manual reverse-engineering
//! task. See `docs/RE_PATCH.md`.

use std::fs::File;
use std::io::{Cursor, Write};
use std::path::Path;

use serde_json::json;
use zip::{write::SimpleFileOptions, ZipWriter};

use crate::error::{Result, RoflError};

#[derive(Debug)]
pub struct PeSection {
    pub name: String,
    pub rva: u32,
    pub virt_size: u32,
    pub raw_offset: u32,
    pub raw_size: u32,
}

#[derive(Debug)]
pub struct PeInfo {
    pub machine: u16,
    pub sections: Vec<PeSection>,
}

/// Parse just enough of the PE file to locate `.text`, `.data`, `.rdata`.
pub fn parse_pe(bytes: &[u8]) -> Result<PeInfo> {
    if bytes.len() < 0x40 {
        return Err(pe_err("file too short for DOS header"));
    }
    if &bytes[0..2] != b"MZ" {
        return Err(pe_err("missing MZ signature"));
    }
    let pe_off =
        u32::from_le_bytes(bytes[0x3C..0x40].try_into().unwrap()) as usize;
    if bytes.len() < pe_off + 24 {
        return Err(pe_err("PE header truncated"));
    }
    if &bytes[pe_off..pe_off + 4] != b"PE\0\0" {
        return Err(pe_err("missing PE signature"));
    }
    let machine = u16::from_le_bytes(bytes[pe_off + 4..pe_off + 6].try_into().unwrap());
    let num_sections =
        u16::from_le_bytes(bytes[pe_off + 6..pe_off + 8].try_into().unwrap()) as usize;
    let opt_header_size =
        u16::from_le_bytes(bytes[pe_off + 20..pe_off + 22].try_into().unwrap()) as usize;

    let sec_start = pe_off + 24 + opt_header_size;
    let mut sections = Vec::with_capacity(num_sections);
    for i in 0..num_sections {
        let base = sec_start + 40 * i;
        if bytes.len() < base + 40 {
            return Err(pe_err("section header truncated"));
        }
        let name_bytes = &bytes[base..base + 8];
        let name_end = name_bytes
            .iter()
            .position(|b| *b == 0)
            .unwrap_or(name_bytes.len());
        let name = String::from_utf8_lossy(&name_bytes[..name_end]).into_owned();
        let virt_size = u32::from_le_bytes(bytes[base + 8..base + 12].try_into().unwrap());
        let rva = u32::from_le_bytes(bytes[base + 12..base + 16].try_into().unwrap());
        let raw_size = u32::from_le_bytes(bytes[base + 16..base + 20].try_into().unwrap());
        let raw_offset = u32::from_le_bytes(bytes[base + 20..base + 24].try_into().unwrap());
        sections.push(PeSection {
            name,
            rva,
            virt_size,
            raw_offset,
            raw_size,
        });
    }
    Ok(PeInfo { machine, sections })
}

/// Write a `.patch`-style zip archive at `output_path` with the three
/// sections (`text.bin` / `data.bin` / `rdata.bin`) plus a `result.json`
/// skeleton. Returns the PE info for the caller to print.
pub fn extract_skeleton(binary_path: &Path, output_path: &Path) -> Result<PeInfo> {
    let bytes = std::fs::read(binary_path)?;
    let pe = parse_pe(&bytes)?;

    let text = pe
        .sections
        .iter()
        .find(|s| s.name == ".text")
        .ok_or_else(|| pe_err("no .text section"))?;
    let data = pe
        .sections
        .iter()
        .find(|s| s.name == ".data")
        .ok_or_else(|| pe_err("no .data section"))?;
    let rdata = pe
        .sections
        .iter()
        .find(|s| s.name == ".rdata")
        .ok_or_else(|| pe_err("no .rdata section"))?;

    let mut buf = Vec::new();
    let mut zip = ZipWriter::new(Cursor::new(&mut buf));
    let opts: SimpleFileOptions =
        SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    for (name, sec) in [
        ("text.bin", text),
        ("data.bin", data),
        ("rdata.bin", rdata),
    ] {
        let start = sec.raw_offset as usize;
        let end = start + sec.raw_size.min(sec.virt_size) as usize;
        if end > bytes.len() {
            return Err(pe_err(&format!(
                "section {name} raw range [{start}..{end}) overruns file"
            )));
        }
        zip.start_file(name, opts)
            .map_err(|e| pe_err(&format!("zip start {name}: {e}")))?;
        zip.write_all(&bytes[start..end])?;
    }

    // result.json skeleton. Values marked NEEDS_RE must be filled in by
    // manual reverse engineering against the binary. See docs/RE_PATCH.md.
    let result_json = json!({
        "_comment": "Skeleton generated by `rofl-x extract-patch`. Fields marked NEEDS_RE must be filled in by reverse-engineering the binary; see docs/RE_PATCH.md for methodology.",
        "player_id_start": "NEEDS_RE",
        "alloc1_rva": "NEEDS_RE",
        "alloc2_rva": "NEEDS_RE",
        "skip_rva": "NEEDS_RE",
        "mov_decrypt": {
            "netid": 0,
            "rva_start": "NEEDS_RE",
            "rva_end": "NEEDS_RE",
            "payload_offset": "0x18",
            "payload_size_offset": "0x20"
        },
        "ward_spawn_decrypt": {
            "netid": 0,
            "rva_start": "NEEDS_RE",
            "rva_end": "NEEDS_RE",
            "id_offset": "NEEDS_RE",
            "owner_id_offset": "NEEDS_RE",
            "name_offset": "NEEDS_RE",
            "name_len_offset": "NEEDS_RE",
            "x_offset": "NEEDS_RE",
            "x_write_count": "NEEDS_RE",
            "y_offset": "NEEDS_RE",
            "y_write_count": "NEEDS_RE"
        },
        "text":  { "rva": format!("0x{:x}", text.rva),  "size": text.virt_size as u64 },
        "data":  { "rva": format!("0x{:x}", data.rva),  "size": data.virt_size as u64 },
        "rdata": { "rva": format!("0x{:x}", rdata.rva), "size": rdata.virt_size as u64 }
    });
    zip.start_file("result.json", opts)
        .map_err(|e| pe_err(&format!("zip start result.json: {e}")))?;
    zip.write_all(
        serde_json::to_string_pretty(&result_json)?
            .as_bytes(),
    )?;
    zip.finish()
        .map_err(|e| pe_err(&format!("zip finish: {e}")))?;

    let mut out = File::create(output_path)?;
    out.write_all(&buf)?;
    Ok(pe)
}

fn pe_err(msg: &str) -> RoflError {
    RoflError::Io(std::io::Error::new(
        std::io::ErrorKind::InvalidData,
        msg.to_string(),
    ))
}
